### ISSUE TITLE
Saving comments doesn't work as expected

### ISSUE THREAD

**Issue by SeriousMartin** [HakanL/resxtranslator#19]
Hi, I found a few problems when it comes to saving comments.
I think it's a mixture of bugs and unexpected behavior (design).

This is how the translator currently works:
1. When I edit only the comment and save, the comment is not saved
2. When I edit the comment of one key and a value of another key, the comment is still not saved
3. When I edit the comment and values of the same key, the comment is saved for every modified language
4. When an entry in the main language file does not have a comment, the comment of another language is loaded

I have attached two resx files to reproduce this.
[I18n.zip](https://github.com/HakanL/resxtranslator/files/1175600/I18n.zip)

This is what I would expect:
If there is only one comment column, it should be the one from the main language. All magic that sometimes doesn't save it and sometimes saves it to multiple files doesn't really help, because user's mostly wont understand it.

- only load the comment from the main language
- the comment should always be saved in the main language
- existing comments in other languages should best stay the way they are

This is how it would be perfect for our purposes. What do you think about it?

PS: An nice-to-have for later: There could be an option to select which language's comment is currently edited. This would require the software to keep all columns in memory, so the user can switch at any time. Alternatively the user could be allowed to display the comments of other languages in addition to the main comment. All of this could be controlled in the "Displayed languages" section.

**Comment by Klocman** [comment]
Hello!

In my experience, there is no real use for multilanguage comments, since they would have to be translated by the translators themselves (whom need to read those comments in English anyways), so I think it's a waste of time.

It would be possible to separate the comments and keep them between different language resources, but it would require changing a sizable chunk of code. (Copying the comment is how the app was originally designed, and stuff was built up with that in mind)

Personally I don't see enough merit to do this, but if anyone implements this, I'll happily accept the pull request.

**Comment by SeriousMartin** [comment]
> In my experience, there is no real use for multilanguage comments,
You are right - we also don't have a need for comments in the translation files.

But currently the translator saves the comments to neutral file **or** any of the the translation files (depending on what other columns where edited). 

When you don't change anything else the changes in the comment column aren't saved at all.

In other words: Currently the translator does multilanguage comments - in a way that is not easy to work with.

I think the three points mentioned above would be a good fix for the problem. No need to add any multi-language stuff.

**Comment by Klocman** [comment]
The bugs with saving definitely need to be fixed. I'll make it always save identical comments to all files when the comment is changed.

I'm opting to keep the comments in all language files, because some projects only have translations without the default file with no language code. In that case should the comment be put on only the first item, all of them, or none? Only first would be unpredictable.
Then, what if the default translation is added? The comment would disappear if we didn't search all files for comments.
Some people also only send around single language resources for proofing, so the comment would be lost as well.

**Comment by SeriousMartin** [comment]
Sounds like a good solution. Thanks!

**Comment by Klocman** [comment]
Fixed the save issue, the logic that decided if a row changed and needed to be rewritten ignored comments.
